### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by sal-git** [chucknezi/lomaschafa#1]
Hola amigo, 

¿Puedes poner un archivo? I can't fork. Make a dummy project and I'll start connecting the MongoDB with schema, routes, etc. Maybe even start a registration logic -- passport.js?

Regards, 
Boca Chica boy

**Comment by chucknezi** [comment]
Que onda wey?

Mira lo que hice. You should be able to fork. Can we make a google doc for collab purposes? 50/50 equity split once this thing takes off.

Saludos, 
Moreno you can't containo
